In [1]:
import pandas as pd

df = pd.read_csv("../data/repositories.csv")

df.head()

,name,description,stars,forks,language,topics,updated_at,license,url
0,tensorflow/tensorflow,An Open Source Machine Learning Framework for ...,198782,76232,C++,"['deep-learning', 'deep-neural-networks', 'dis...",2026-09-03T15:59:55Z,Apache License 2.0,https://github.com/tensorflow/tensorflow
1,huggingface/transformers,🤗 Transformers: the model-definition framework...,164741,34432,Python,"['audio', 'deep-learning', 'deepseek', 'gemma'...",2026-09-03T15:56:43Z,Apache License 2.0,https://github.com/huggingface/transformers
2,microsoft/ML-For-Beginners,"12 weeks, 26 lessons, 52 quizzes, classic Mach...",90085,22169,Jupyter Notebook,"['data-science', 'education', 'machine-learnin...",2026-09-03T16:04:42Z,MIT License,https://github.com/microsoft/ML-For-Beginners
3,fighting41love/funNLP,中英文敏感词、语言检测、中外手机/电话归属地/运营商查询、名字推断性别、手机号抽取、身份证抽...,82853,15279,Python,[],2026-09-03T16:05:59Z,NaN,https://github.com/fighting41love/funNLP
4,josephmisiti/awesome-machine-learning,A curated list of awesome Machine Learning fra...,74245,15638,Python,[],2026-09-03T15:56:28Z,Other,https://github.com/josephmisiti/awesome-machin...

In [2]:
df.shape

(10, 9)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         10 non-null     str
 1   description  10 non-null     str
 2   stars        10 non-null     int64
 3   forks        10 non-null     int64
 4   language     9 non-null      str
 5   topics       10 non-null     str
 6   updated_at   10 non-null     str
 7   license      8 non-null      str
 8   url          10 non-null     str
dtypes: int64(2), str(7)
memory usage: 852.0 bytes

In [4]:
df.isnull().sum()

name           0
description    0
stars          0
forks          0
language       1
topics         0
updated_at     0
license        2
url            0
dtype: int64

In [5]:
df["language"].value_counts()

language
Python              5
C++                 2
Jupyter Notebook    1
JavaScript          1
Name: count, dtype: int64

In [6]:
df.columns

Index(['name', 'description', 'stars', 'forks', 'language', 'topics',
       'updated_at', 'license', 'url'],
      dtype='str')

In [7]:
df[["name", "description"]]

,name,description
0,tensorflow/tensorflow,An Open Source Machine Learning Framework for ...
1,huggingface/transformers,🤗 Transformers: the model-definition framework...
2,microsoft/ML-For-Beginners,"12 weeks, 26 lessons, 52 quizzes, classic Mach..."
3,fighting41love/funNLP,中英文敏感词、语言检测、中外手机/电话归属地/运营商查询、名字推断性别、手机号抽取、身份证抽...
4,josephmisiti/awesome-machine-learning,A curated list of awesome Machine Learning fra...
5,scikit-learn/scikit-learn,scikit-learn: machine learning in Python
6,gradio-app/gradio,Build and share delightful machine learning ap...
7,ashishpatel26/500-AI-Machine-learning-Deep-lea...,500 AI Machine learning Deep learning Computer...
8,TheAlgorithms/C-Plus-Plus,Collection of various algorithms in mathematic...
9,lutzroeder/netron,"Visualizer for neural network, deep learning a..."

In [8]:
df["name"].duplicated().sum()

np.int64(0)

In [9]:
df["description"].isna().sum()

np.int64(0)

In [10]:
df["description"].fillna("").str.len().describe()

count      10.000000
mean      662.500000
std      1817.865858
min        40.000000
25%        67.500000
50%        77.000000
75%       128.000000
max      5835.000000
Name: description, dtype: float64

In [11]:
df["topics"]

0    ['deep-learning', 'deep-neural-networks', 'dis...
1    ['audio', 'deep-learning', 'deepseek', 'gemma'...
2    ['data-science', 'education', 'machine-learnin...
3                                                   []
4                                                   []
5    ['data-analysis', 'data-science', 'machine-lea...
6    ['data-analysis', 'data-science', 'data-visual...
7    ['artificial-intelligence', 'artificial-intell...
8    ['algorithm', 'algorithm-competitions', 'algor...
9    ['ai', 'coreml', 'deep-learning', 'deeplearnin...
Name: topics, dtype: str