In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r'C:\Users\ayush\PROJECTS\Github-Recommender\Data\repositories.csv')
df

,name,description,stars,forks,language,topics,updated_at,license,url,readme
0,tensorflow/tensorflow,An Open Source Machine Learning Framework for ...,199328,76290,C++,"['deep-learning', 'deep-neural-networks', 'dis...",2026-09-07T14:45:44Z,Apache License 2.0,https://github.com/tensorflow/tensorflow,"<div align=""center"">\n <img src=""https://www...."
1,huggingface/transformers,🤗 Transformers: the model-definition framework...,164954,34483,Python,"['audio', 'deep-learning', 'deepseek', 'gemma'...",2026-09-07T14:45:18Z,Apache License 2.0,https://github.com/huggingface/transformers,<!---\nCopyright 2020 The HuggingFace Team. Al...
2,microsoft/ML-For-Beginners,"12 weeks, 26 lessons, 52 quizzes, classic Mach...",90242,22203,Jupyter Notebook,"['data-science', 'education', 'machine-learnin...",2026-09-07T14:30:47Z,MIT License,https://github.com/microsoft/ML-For-Beginners,[![GitHub license](https://img.shields.io/gith...
3,fighting41love/funNLP,中英文敏感词、语言检测、中外手机/电话归属地/运营商查询、名字推断性别、手机号抽取、身份证抽...,82938,15277,Python,[],2026-09-07T14:29:49Z,NaN,https://github.com/fighting41love/funNLP,"<center>\n <img style=""border-radius: 0.312..."
4,josephmisiti/awesome-machine-learning,A curated list of awesome Machine Learning fra...,74274,15638,Python,[],2026-09-07T14:33:36Z,Other,https://github.com/josephmisiti/awesome-machin...,# Awesome Machine Learning [![Awesome](https:/...
...,...,...,...,...,...,...,...,...,...,...
456,PacktPublishing/LLM-Engineers-Handbook,The LLM's practical guide: From the fundamenta...,5315,1289,Python,"['aws', 'fine-tuning-llm', 'genai', 'llm', 'll...",2026-09-06T00:40:19Z,MIT License,https://github.com/PacktPublishing/LLM-Enginee...,<p align='center'><a href='https://www.packtpu...
457,kelvins/awesome-mlops,:sunglasses: A curated list of awesome MLOps t...,5266,775,Python,"['ai', 'awesome', 'data-science', 'machine-lea...",2026-09-06T15:43:47Z,NaN,https://github.com/kelvins/awesome-mlops,# Awesome MLOps [![Awesome](https://cdn.rawgit...
458,argilla-io/argilla,Argilla is a collaboration tool for AI enginee...,5101,506,Python,"['active-learning', 'ai', 'annotation-tool', '...",2026-09-07T12:27:00Z,Apache License 2.0,https://github.com/argilla-io/argilla,> [!IMPORTANT]\nThe original authors have move...
459,tencentmusic/cube-studio,cube studio开源云原生一站式机器学习/深度学习/大模型AI平台，mlops算法链路...,5077,880,NaN,"['ai', 'aihub', 'argo', 'automl', 'deepseek', ...",2026-09-06T05:39:12Z,Other,https://github.com/tencentmusic/cube-studio,# 仓库已归档\n\n本仓库已于 2026-05-18 归档，不再维护。 [跳转至新仓库]...
460,SeldonIO/seldon-core,"An MLOps framework to package, deploy, monitor...",4779,867,Go,"['aiops', 'deployment', 'kubernetes', 'machine...",2026-09-07T04:23:52Z,Other,https://github.com/SeldonIO/seldon-core,"<div align=""center"">\n\n <a href=""https://www...."

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 461 entries, 0 to 460
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         461 non-null    str
 1   description  457 non-null    str
 2   stars        461 non-null    int64
 3   forks        461 non-null    int64
 4   language     396 non-null    str
 5   topics       461 non-null    str
 6   updated_at   461 non-null    str
 7   license      390 non-null    str
 8   url          461 non-null    str
 9   readme       461 non-null    str
dtypes: int64(2), str(8)
memory usage: 36.1 KB

In [4]:
df.describe()

               stars         forks
count     461.000000    461.000000
mean    15056.633406   3286.310195
std     25408.382229   7326.094726
min      1179.000000     26.000000
25%      4360.000000    630.000000
50%      8032.000000   1349.000000
75%     17469.000000   3408.000000
max    368503.000000  76290.000000

In [5]:
df.isnull().sum()

name            0
description     4
stars           0
forks           0
language       65
topics          0
updated_at      0
license        71
url             0
readme          0
dtype: int64

In [6]:
df["language"].value_counts()

language
Python              172
Jupyter Notebook     72
JavaScript           33
TypeScript           27
C++                  24
Go                   14
HTML                  9
Java                  6
Rust                  6
TeX                   5
C                     4
C#                    4
Shell                 4
Ruby                  3
MDX                   3
PHP                   2
Scala                 1
CSS                   1
Dart                  1
R                     1
SCSS                  1
Astro                 1
Markdown              1
MATLAB                1
Name: count, dtype: int64

In [7]:
import pandas as pd
df=pd.read_csv(r'C:\Users\ayush\PROJECTS\Github-Recommender\Data\repositories.csv')
df

,name,description,stars,forks,language,topics,updated_at,license,url,readme
0,tensorflow/tensorflow,An Open Source Machine Learning Framework for ...,199328,76290,C++,"['deep-learning', 'deep-neural-networks', 'dis...",2026-09-07T14:45:44Z,Apache License 2.0,https://github.com/tensorflow/tensorflow,"<div align=""center"">\n <img src=""https://www...."
1,huggingface/transformers,🤗 Transformers: the model-definition framework...,164954,34483,Python,"['audio', 'deep-learning', 'deepseek', 'gemma'...",2026-09-07T14:45:18Z,Apache License 2.0,https://github.com/huggingface/transformers,<!---\nCopyright 2020 The HuggingFace Team. Al...
2,microsoft/ML-For-Beginners,"12 weeks, 26 lessons, 52 quizzes, classic Mach...",90242,22203,Jupyter Notebook,"['data-science', 'education', 'machine-learnin...",2026-09-07T14:30:47Z,MIT License,https://github.com/microsoft/ML-For-Beginners,[![GitHub license](https://img.shields.io/gith...
3,fighting41love/funNLP,中英文敏感词、语言检测、中外手机/电话归属地/运营商查询、名字推断性别、手机号抽取、身份证抽...,82938,15277,Python,[],2026-09-07T14:29:49Z,NaN,https://github.com/fighting41love/funNLP,"<center>\n <img style=""border-radius: 0.312..."
4,josephmisiti/awesome-machine-learning,A curated list of awesome Machine Learning fra...,74274,15638,Python,[],2026-09-07T14:33:36Z,Other,https://github.com/josephmisiti/awesome-machin...,# Awesome Machine Learning [![Awesome](https:/...
...,...,...,...,...,...,...,...,...,...,...
456,PacktPublishing/LLM-Engineers-Handbook,The LLM's practical guide: From the fundamenta...,5315,1289,Python,"['aws', 'fine-tuning-llm', 'genai', 'llm', 'll...",2026-09-06T00:40:19Z,MIT License,https://github.com/PacktPublishing/LLM-Enginee...,<p align='center'><a href='https://www.packtpu...
457,kelvins/awesome-mlops,:sunglasses: A curated list of awesome MLOps t...,5266,775,Python,"['ai', 'awesome', 'data-science', 'machine-lea...",2026-09-06T15:43:47Z,NaN,https://github.com/kelvins/awesome-mlops,# Awesome MLOps [![Awesome](https://cdn.rawgit...
458,argilla-io/argilla,Argilla is a collaboration tool for AI enginee...,5101,506,Python,"['active-learning', 'ai', 'annotation-tool', '...",2026-09-07T12:27:00Z,Apache License 2.0,https://github.com/argilla-io/argilla,> [!IMPORTANT]\nThe original authors have move...
459,tencentmusic/cube-studio,cube studio开源云原生一站式机器学习/深度学习/大模型AI平台，mlops算法链路...,5077,880,NaN,"['ai', 'aihub', 'argo', 'automl', 'deepseek', ...",2026-09-06T05:39:12Z,Other,https://github.com/tencentmusic/cube-studio,# 仓库已归档\n\n本仓库已于 2026-05-18 归档，不再维护。 [跳转至新仓库]...
460,SeldonIO/seldon-core,"An MLOps framework to package, deploy, monitor...",4779,867,Go,"['aiops', 'deployment', 'kubernetes', 'machine...",2026-09-07T04:23:52Z,Other,https://github.com/SeldonIO/seldon-core,"<div align=""center"">\n\n <a href=""https://www...."

In [8]:
df['readme'].isnull().sum()

np.int64(0)

In [9]:
(df["readme"] == "").sum()

np.int64(0)

In [10]:
df["readme"].str.len().describe()

count       461.000000
mean      27323.401302
std       58469.126703
min         288.000000
25%        5259.000000
50%       10241.000000
75%       23131.000000
max      510809.000000
Name: readme, dtype: float64

In [11]:
df[["name", "readme"]].head(5)

,name,readme
0,tensorflow/tensorflow,"<div align=""center"">\n <img src=""https://www...."
1,huggingface/transformers,<!---\nCopyright 2020 The HuggingFace Team. Al...
2,microsoft/ML-For-Beginners,[![GitHub license](https://img.shields.io/gith...
3,fighting41love/funNLP,"<center>\n <img style=""border-radius: 0.312..."
4,josephmisiti/awesome-machine-learning,# Awesome Machine Learning [![Awesome](https:/...

In [12]:
print("Empty READMEs:", (df["readme"] == "").sum())

Empty READMEs: 0

In [57]:
df.columns

Index(['name', 'description', 'stars', 'forks', 'language', 'topics',
       'updated_at', 'license', 'url', 'readme', 'combined_text',
       'clean_text'],
      dtype='str')

In [14]:
df["combined_text"] = (
    df["name"].fillna("") + " " +
    df["description"].fillna("") + " " +
    df["topics"].fillna("") + " " +
    df["readme"].fillna("")
)

In [15]:
df['combined_text'].head()

0    tensorflow/tensorflow An Open Source Machine L...
1    huggingface/transformers 🤗 Transformers: the m...
2    microsoft/ML-For-Beginners 12 weeks, 26 lesson...
3    fighting41love/funNLP 中英文敏感词、语言检测、中外手机/电话归属地/运...
4    josephmisiti/awesome-machine-learning A curate...
Name: combined_text, dtype: str

In [16]:
df[["name", "combined_text"]].head(2)

                       name                                      combined_text
0     tensorflow/tensorflow  tensorflow/tensorflow An Open Source Machine L...
1  huggingface/transformers  huggingface/transformers 🤗 Transformers: the m...

In [17]:
df["combined_text"].isnull().sum()

np.int64(0)

In [18]:
df["combined_text"].str.len().describe()

count       461.000000
mean      27616.967462
std       58501.534420
min         412.000000
25%        5511.000000
50%       10506.000000
75%       23584.000000
max      511138.000000
Name: combined_text, dtype: float64

In [19]:
import re
import html


def clean_text(text):
    
    # Convert anything that isn't text into an empty string
    text = str(text)

    # Decode HTML entities
    text = html.unescape(text)

    # Remove HTML tags
    text = re.sub(r"<[^>]+>", " ", text)

    # Remove URLs
    text = re.sub(r"https?://\S+|www\.\S+", " ", text)

    # Remove Markdown images
    text = re.sub(r"!\[.*?\]\(.*?\)", " ", text)

    # Remove Markdown links but keep the link text
    text = re.sub(r"\[(.*?)\]\(.*?\)", r"\1", text)

    # Remove excessive whitespace
    text = re.sub(r"\s+", " ", text)

    # Remove leading/trailing spaces
    text = text.strip()

    return text

In [20]:
df["clean_text"] = df["combined_text"].apply(clean_text)

In [21]:
print("BEFORE:\n")
print(df.loc[0, "combined_text"][:1000])

print("\n\nAFTER:\n")
print(df.loc[0, "clean_text"][:1000])

BEFORE:

tensorflow/tensorflow An Open Source Machine Learning Framework for Everyone ['deep-learning', 'deep-neural-networks', 'distributed', 'machine-learning', 'ml', 'neural-network', 'python', 'tensorflow'] <div align="center">
  <img src="https://www.tensorflow.org/images/tf_logo_horizontal.png">
</div>

[![Python](https://img.shields.io/pypi/pyversions/tensorflow.svg)](https://badge.fury.io/py/tensorflow)
[![PyPI](https://badge.fury.io/py/tensorflow.svg)](https://badge.fury.io/py/tensorflow)
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.4724125.svg)](https://doi.org/10.5281/zenodo.4724125)
[![CII Best Practices](https://bestpractices.coreinfrastructure.org/projects/1486/badge)](https://bestpractices.coreinfrastructure.org/projects/1486)
[![OpenSSF Scorecard](https://api.securityscorecards.dev/projects/github.com/tensorflow/tensorflow/badge)](https://securityscorecards.dev/viewer/?uri=github.com/tensorflow/tensorflow)
[![Fuzzing Status](https://oss-fuzz-build-logs.storage.googleapis.


AFTER:

tensorflow/tensorflow An Open Source Machine Learning Framework for Everyone ['deep-learning', 'deep-neural-networks', 'distributed', 'machine-learning', 'ml', 'neural-network', 'python', 'tensorflow'] [![Python]( [![PyPI]( [![DOI]( [![CII Best Practices]( [![OpenSSF Scorecard]( [![Fuzzing Status]( [![Fuzzing Status]( [![OSSRank]( [![Contributor Covenant]( **`Documentation`** | ------------------- | [![Documentation]( | [TensorFlow]( is an end-to-end open source platform for machine learning. It has a comprehensive, flexible ecosystem of [tools]( [libraries]( and [community]( resources that lets researchers push the state-of-the-art in ML and developers easily build and deploy ML-powered applications. TensorFlow was originally developed by researchers and engineers working within the Machine Intelligence team at Google Brain to conduct research in machine learning and neural networks. However, the framework is versatile enough to be used in other areas as well. TensorFlow provides stab

In [22]:
print("Missing clean_text:", df["clean_text"].isna().sum())

print(
    "Empty clean_text:",
    (df["clean_text"].str.strip() == "").sum()
)

Missing clean_text: 0
Empty clean_text: 0

In [23]:
df["clean_text"].str.len().describe()

count       461.000000
mean      14103.123644
std       23991.561666
min         174.000000
25%        3336.000000
50%        6332.000000
75%       13198.000000
max      194914.000000
Name: clean_text, dtype: float64

In [24]:
df.head()

,name,description,stars,forks,language,topics,updated_at,license,url,readme,combined_text,clean_text
0,tensorflow/tensorflow,An Open Source Machine Learning Framework for ...,199328,76290,C++,"['deep-learning', 'deep-neural-networks', 'dis...",2026-09-07T14:45:44Z,Apache License 2.0,https://github.com/tensorflow/tensorflow,"<div align=""center"">\n <img src=""https://www....",tensorflow/tensorflow An Open Source Machine L...,tensorflow/tensorflow An Open Source Machine L...
1,huggingface/transformers,🤗 Transformers: the model-definition framework...,164954,34483,Python,"['audio', 'deep-learning', 'deepseek', 'gemma'...",2026-09-07T14:45:18Z,Apache License 2.0,https://github.com/huggingface/transformers,<!---\nCopyright 2020 The HuggingFace Team. Al...,huggingface/transformers 🤗 Transformers: the m...,huggingface/transformers 🤗 Transformers: the m...
2,microsoft/ML-For-Beginners,"12 weeks, 26 lessons, 52 quizzes, classic Mach...",90242,22203,Jupyter Notebook,"['data-science', 'education', 'machine-learnin...",2026-09-07T14:30:47Z,MIT License,https://github.com/microsoft/ML-For-Beginners,[![GitHub license](https://img.shields.io/gith...,"microsoft/ML-For-Beginners 12 weeks, 26 lesson...","microsoft/ML-For-Beginners 12 weeks, 26 lesson..."
3,fighting41love/funNLP,中英文敏感词、语言检测、中外手机/电话归属地/运营商查询、名字推断性别、手机号抽取、身份证抽...,82938,15277,Python,[],2026-09-07T14:29:49Z,NaN,https://github.com/fighting41love/funNLP,"<center>\n <img style=""border-radius: 0.312...",fighting41love/funNLP 中英文敏感词、语言检测、中外手机/电话归属地/运...,fighting41love/funNLP 中英文敏感词、语言检测、中外手机/电话归属地/运...
4,josephmisiti/awesome-machine-learning,A curated list of awesome Machine Learning fra...,74274,15638,Python,[],2026-09-07T14:33:36Z,Other,https://github.com/josephmisiti/awesome-machin...,# Awesome Machine Learning [![Awesome](https:/...,josephmisiti/awesome-machine-learning A curate...,josephmisiti/awesome-machine-learning A curate...

In [25]:
from sentence_transformers import SentenceTransformer

In [26]:
model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

model.safetensors: reconstructing file:   0%|          |  0.00B /  471MB

model.safetensors: downloading bytes:           |  0.00B

c:\Users\ayush\PROJECTS\Github-Recommender\.venv\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\ayush\.cache\huggingface\hub\models--sentence-transformers--paraphrase-multilingual-MiniLM-L12-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/526 [00:00<?, ?B/s]

tokenizer.json: reconstructing file:   0%|          |  0.00B / 9.08MB

tokenizer.json: downloading bytes:           |  0.00B

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
text = "Python machine learning project for image classification"

embeddingss = model.encode(text)

print(embeddingss)
print("Embedding dimensions:", len(embeddingss))

[-5.75371161e-02  1.02679152e-02  1.18176207e-01 -6.72927424e-02
  9.62052494e-02  3.02910030e-01  1.49312124e-01 -2.90326923e-01
 -8.41618925e-02  2.03183025e-01 -5.69147640e-04 -1.14505693e-01
  2.31919408e-01  3.19571830e-02 -8.05564106e-01 -4.46158111e-01
  3.03598400e-02  9.68746841e-02  1.33908644e-01 -3.74649376e-01
  2.37909555e-01 -1.55118570e-01  3.64984691e-01 -1.29367664e-01
  7.39104226e-02 -3.25635403e-01 -8.38273787e-04 -6.72142655e-02
  2.50694513e-01 -3.84691089e-01  1.44036278e-01  1.36292707e-02
  1.01425946e+00  2.15799063e-01 -3.15153539e-01  1.33614823e-01
 -2.11328551e-01  2.32223675e-01  8.31133723e-02 -9.01994705e-02
 -1.54307038e-01 -1.77981019e-01 -6.75798804e-02 -1.26683801e-01
  7.74007067e-02 -6.12985119e-02 -2.62231052e-01 -1.25325024e-01
 -3.82300317e-01 -1.86696649e-01  8.70682746e-02 -2.41735458e-01
  3.32274921e-02 -5.92405796e-01  2.57689655e-01 -7.43876621e-02
  2.51587600e-01 -1.77167982e-01 -3.29333782e-01 -7.16592371e-02
 -1.26705989e-01  2.34892413e-01  2.05329657e-02  1.04326829e-01
  2.20704600e-01  2.63544589e-01  7.10974112e-02 -5.50886281e-02
  2.80501753e-01 -2.17129990e-01 -5.49184456e-02  4.45877053e-02
 -3.82734597e-01 -1.53844029e-01 -2.97173679e-01  3.34437013e-01
  1.90276831e-01  1.16114832e-01 -7.18451589e-02 -3.31561193e-02
  1.23308085e-01  5.86624853e-02  2.91126519e-01  9.46833789e-02
  3.70750129e-01  2.78481066e-01 -2.63030883e-02 -6.40654340e-02
 -3.41344237e-01 -4.94965501e-02  3.69835421e-02 -7.06817070e-03
 -8.84834900e-02  3.44712347e-01 -1.92860395e-01 -7.04810023e-02
 -1.73333496e-01 -4.84607458e-01  2.27762133e-01  5.48932374e-01
 -4.49559748e-01 -1.56911612e-02 -3.24369013e-01 -2.22680375e-01
  1.14370421e-01  1.55232504e-01 -1.22704938e-01 -2.18920380e-01
  1.39340293e-02 -6.09283745e-02  1.70135364e-01 -1.00104548e-01
 -1.31489724e-01  9.54326913e-02  7.34270215e-02 -3.59992497e-02
  5.45590036e-02  4.81751151e-02  1.14867471e-01 -1.39948413e-01
  9.39338058e-02 -9.86989588e-02  1.66485012e-01  2.41450816e-01
  2.47454613e-01 -3.68614823e-01 -2.74587333e-01 -1.32401481e-01
  2.71436963e-02 -2.96816111e-01  4.41587836e-01 -1.33144617e-01
  3.94537866e-01  1.57205194e-01  1.99831650e-01  4.01650280e-01
 -3.25306877e-02 -1.98646992e-01 -3.80253017e-01  1.87686890e-01
  1.21723991e-02  9.73818526e-02  1.28935292e-01  4.33598846e-01
 -7.33897537e-02  1.37076765e-01 -1.37654573e-01 -1.67934626e-01
  5.24697416e-02  3.22933048e-02 -2.11240619e-01 -4.50089842e-01
  3.86429355e-02  1.62557319e-01  2.31087685e-01  2.47743323e-01
  1.67150602e-01 -7.16374442e-03 -1.39997810e-01 -2.22797394e-01
 -3.71299654e-01 -1.22112036e-01 -1.15069069e-01 -2.64432967e-01
 -5.12193978e-01 -1.28368467e-01  3.07201445e-02  5.47658578e-02
  2.69460734e-02  1.60440534e-01  1.34114623e-01 -2.30851009e-01
 -2.43264914e-01  2.90537715e-01  4.97307666e-02  3.42048526e-01
 -3.00844133e-01 -4.95146737e-02  4.03556913e-01 -1.35871559e-01
 -9.91386473e-02 -1.03213988e-01  1.38965353e-01 -1.06798753e-01
 -1.14580337e-02 -3.69376503e-02  7.43316580e-03 -2.06153661e-01
  5.40161729e-02  2.52674729e-01  3.09083998e-01 -2.57930700e-02
  3.00051004e-01 -5.81162944e-02 -1.68731846e-02  8.94491524e-02
  4.36823219e-01  2.18708068e-02 -3.64069879e-01 -3.84395532e-02
 -3.38641226e-01 -8.79839435e-02 -2.35242605e-01 -2.71005243e-01
 -3.96892548e-01 -1.03837848e-01  5.18966690e-02  4.87488747e-01
 -1.39599785e-01  6.12155557e-01 -3.11948240e-01 -1.07117910e-02
 -4.37925488e-01 -1.90408185e-01  2.94347644e-01  9.38141067e-03
 -8.48806277e-03 -2.78080940e-01 -2.31481679e-02  2.19231203e-01
  1.64236724e-01 -8.59844908e-02 -1.00080349e-01  5.60017228e-02
 -1.42299682e-01  3.00326347e-01 -1.39347073e-02 -1.45630747e-01
 -2.50896037e-01 -2.40041643e-01  1.50487348e-01 -1.56005040e-01
 -1.43967241e-01  1.07209302e-01 -1.83851290e-02 -4.93673235e-03
 -4.45981741e-01 -3.55060428e-01  1.36185080e-01  2.91141838e-01
 -1.10582009e-01 -4.57145199e-02 -1.50012746e-01  5.66388480e-02
 -8.10880736e-02  3.72581959e-01  2.77192555e-02 -2.75472611e-01
 -1.69797406e-01  2.60526448e-01  1.72162026e-01 -1.25636980e-01
  4.62536395e-01 -5.49301915e-02  1.64764002e-01 -6.78801119e-01
 -1.19707748e-01  3.29179287e-01 -1.11169659e-01 -7.64351040e-02
  2.66804665e-01 -1.86233088e-01  2.20805138e-01  3.07899535e-01
 -1.82651505e-01 -8.80493224e-02 -3.02346259e-01 -1.20988108e-01
 -3.83821309e-01 -2.35834166e-01  3.97482216e-01  3.66958618e-01
  1.12639904e-01  2.24303082e-01 -4.08569947e-02  7.45778233e-02
  1.91769041e-02  1.37411103e-01 -8.13202336e-02 -1.07194319e-01
 -2.90892988e-01  3.83180618e-01 -2.25096077e-01  2.40628839e-01
 -1.77741513e-01 -2.31600888e-02 -5.69498658e-01  1.79755241e-01
 -4.37912285e-01  8.02462474e-02 -3.75827640e-01  1.13353863e-01
 -2.07905963e-01 -8.59643519e-02 -9.61080223e-05  1.81813747e-01
  2.54423469e-01  2.46309921e-01 -1.14837267e-01  3.01173747e-01
 -4.00944054e-02  4.16053385e-01 -3.86606544e-01  5.60797527e-02
 -4.43964005e-01 -4.01636034e-01  2.82572091e-01  1.83734417e-01
  9.96813551e-02 -1.25602201e-01  6.05182275e-02 -3.77479523e-01
  3.52768004e-01 -1.49978104e-03 -1.67323261e-01 -1.79146200e-01
  2.73497999e-01  4.43099141e-02  3.56772244e-01  6.94148168e-02
 -3.02290618e-01  1.42681822e-01  5.13015211e-01  1.15471758e-01
 -3.07108968e-01  1.63393676e-01 -9.37827826e-02  2.20653459e-01
 -3.39623131e-02 -1.09405115e-01  5.61757758e-02  5.20505896e-03
 -3.24670643e-01  9.27358791e-02  7.50932023e-02  1.19647302e-01
  3.98027599e-01  3.83255392e-01  2.97775626e-01 -1.60391942e-01
  1.82397410e-01 -1.08710803e-01 -5.92048585e-01 -2.06786036e-01
 -8.37427974e-02 -9.47556943e-02 -5.70536070e-02  1.62747115e-01
 -1.90210283e-01 -2.10040167e-01  1.81985453e-01  1.63103715e-01
  2.39199400e-01  2.22692564e-01  7.45242774e-01  2.39114046e-01
 -2.31269240e-01 -2.55970180e-01 -1.93626876e-03  1.40685081e-01
 -1.97926670e-01 -1.47391111e-02  1.28528818e-01 -4.11235154e-01
  4.19316351e-01  1.97182089e-01  2.87359625e-01 -4.18794245e-01
  1.15493849e-01  1.59891341e-02  4.15318552e-03 -2.09749311e-01
  3.08001816e-01  3.15974385e-01  1.43688813e-01  3.23297948e-01
  2.80984014e-01 -1.95391774e-01  6.04801118e-01 -6.41379654e-02
 -1.54790372e-01  3.06887031e-01 -2.42371470e-01 -2.03784749e-01]
Embedding dimensions: 384

In [28]:
embeddings = model.encode(
    df["clean_text"].tolist(),
    show_progress_bar=True
)

Batches:   0%|          | 0/15 [00:00<?, ?it/s]

In [30]:
print(type(embeddings))
print(embeddings.shape)

<class 'numpy.ndarray'>
(461, 384)

In [39]:
import numpy as np

np.save(r"c:\Users\ayush\PROJECTS\Github-Recommender\Data/embeddings.npy", embeddings)

In [40]:
embeddings = np.load(
    r"C:\Users\ayush\PROJECTS\Github-Recommender\Data\embeddings.npy"
)

print(embeddings.shape)

(461, 384)

In [41]:
# Now testing embedding

query = "Find me a Python deep-learning project for image classification."

query_embedding = model.encode(query)

print(query_embedding.shape)

(384,)

In [42]:

from sentence_transformers import util

similarities = util.cos_sim(query_embedding, embeddings)

print(similarities.shape)

torch.Size([1, 461])

In [43]:
similarities = similarities[0]

In [44]:
top_indices = similarities.argsort(descending=True)[:5]

In [46]:
for idx in top_indices:
    idx = idx.item()
    print(df.iloc[idx]["name"])
    print("Similarity:", similarities[idx].item())
    print()

WZMIAOMIAO/deep-learning-for-image-processing
Similarity: 0.759320080280304

aleju/imgaug
Similarity: 0.6562669277191162

OlafenwaMoses/ImageAI
Similarity: 0.6012128591537476

tangyudi/Ai-Learn
Similarity: 0.582196831703186

NVIDIA/DeepLearningExamples
Similarity: 0.5640555024147034

In [47]:
for idx in top_indices:
    idx = idx.item()

    print("Repository:", df.iloc[idx]["name"])
    print("Description:", df.iloc[idx]["description"])
    print("Language:", df.iloc[idx]["language"])
    print("Similarity:", round(similarities[idx].item(), 4))
    print("-" * 60)

Repository: WZMIAOMIAO/deep-learning-for-image-processing
Description: deep learning for image processing including classification and object-detection etc.
Language: Python
Similarity: 0.7593
------------------------------------------------------------
Repository: aleju/imgaug
Description: Image augmentation for machine learning experiments.
Language: Python
Similarity: 0.6563
------------------------------------------------------------
Repository: OlafenwaMoses/ImageAI
Description: A python library built to empower developers to build applications and systems  with self-contained Computer Vision capabilities
Language: Python
Similarity: 0.6012
------------------------------------------------------------
Repository: tangyudi/Ai-Learn
Description: 人工智能学习路线图，整理近200个实战案例与项目，免费提供配套教材，零基础入门，就业实战！包括：Python，数学，机器学习，数据分析，深度学习，计算机视觉，自然语言处理，PyTorch tensorflow machine-learning,deep-learning data-analysis data-mining mathematics data-science artificial-intelligence python tensorflow tensorflow2 caffe keras pytorch algorithm numpy pandas matplotlib seaborn nlp cv等热门领域
Language: nan
Similarity: 0.5822
------------------------------------------------------------
Repository: NVIDIA/DeepLearningExamples
Description: State-of-the-Art Deep Learning scripts organized by models - easy to train and deploy with reproducible accuracy and performance on enterprise-grade infrastructure.
Language: Jupyter Notebook
Similarity: 0.5641
------------------------------------------------------------

In [48]:
def search_repositories(query, top_k=5):

    # Convert user query into embedding
    query_embedding = model.encode(query)

    # Compare query with all repository embeddings
    similarities = util.cos_sim(query_embedding, embeddings)[0]

    # Get top K repository indexes
    top_indices = similarities.argsort(descending=True)[:top_k]

    results = []

    for idx in top_indices:

        idx = idx.item()

        results.append({
            "name": df.iloc[idx]["name"],
            "description": df.iloc[idx]["description"],
            "language": df.iloc[idx]["language"],
            "stars": df.iloc[idx]["stars"],
            "url": df.iloc[idx]["url"],
            "similarity": round(similarities[idx].item(), 4)
        })

    return results

In [49]:
results = search_repositories(
    "Find me a Python deep-learning project for image classification."
)

results

[{'name': 'WZMIAOMIAO/deep-learning-for-image-processing',
  'description': 'deep learning for image processing including classification and object-detection etc.',
  'language': 'Python',
  'stars': np.int64(26372),
  'url': 'https://github.com/WZMIAOMIAO/deep-learning-for-image-processing',
  'similarity': 0.7593},
 {'name': 'aleju/imgaug',
  'description': 'Image augmentation for machine learning experiments.',
  'language': 'Python',
  'stars': np.int64(14740),
  'url': 'https://github.com/aleju/imgaug',
  'similarity': 0.6563},
 {'name': 'OlafenwaMoses/ImageAI',
  'description': 'A python library built to empower developers to build applications and systems  with self-contained Computer Vision capabilities',
  'language': 'Python',
  'stars': np.int64(8882),
  'url': 'https://github.com/OlafenwaMoses/ImageAI',
  'similarity': 0.6012},
 {'name': 'tangyudi/Ai-Learn',
  'description': '人工智能学习路线图，整理近200个实战案例与项目，免费提供配套教材，零基础入门，就业实战！包括：Python，数学，机器学习，数据分析，深度学习，计算机视觉，自然语言处理，PyTorch tensorflow machine-learning,deep-learning data-analysis data-mining mathematics data-science artificial-intelligence python tensorflow tensorflow2 caffe keras pytorch algorithm numpy pandas matplotlib seaborn nlp cv等热门领域',
  'language': nan,
  'stars': np.int64(13325),
  'url': 'https://github.com/tangyudi/Ai-Learn',
  'similarity': 0.5822},
 {'name': 'NVIDIA/DeepLearningExamples',
  'description': 'State-of-the-Art Deep Learning scripts organized by models - easy to train and deploy with reproducible accuracy and performance on enterprise-grade infrastructure.',
  'language': 'Jupyter Notebook',
  'stars': np.int64(14846),
  'url': 'https://github.com/NVIDIA/DeepLearningExamples',
  'similarity': 0.5641}]

In [51]:
rea = search_repositories("Python NLP sentiment analysis")
rea

[{'name': 'shirosaidev/stocksight',
  'description': 'Stock market analyzer and predictor using Elasticsearch, Twitter, News headlines and Python natural language processing and sentiment analysis',
  'language': 'Python',
  'stars': np.int64(2535),
  'url': 'https://github.com/shirosaidev/stocksight',
  'similarity': 0.4902},
 {'name': 'explosion/spaCy',
  'description': '💫 Industrial-strength Natural Language Processing (NLP) in Python',
  'language': 'Python',
  'stars': np.int64(33881),
  'url': 'https://github.com/explosion/spaCy',
  'similarity': 0.48},
 {'name': 'pymupdf/PyMuPDF',
  'description': 'PyMuPDF is a high performance Python library for data extraction, analysis, conversion & manipulation of PDF (and other) documents.',
  'language': 'Python',
  'stars': np.int64(10660),
  'url': 'https://github.com/pymupdf/PyMuPDF',
  'similarity': 0.4732},
 {'name': 'Alfred1984/interesting-python',
  'description': '有趣的Python爬虫和Python数据分析小项目(Some interesting Python crawlers and data analysis projects)',
  'language': 'Jupyter Notebook',
  'stars': np.int64(5007),
  'url': 'https://github.com/Alfred1984/interesting-python',
  'similarity': 0.4453},
 {'name': 'clips/pattern',
  'description': 'Web mining module for Python, with tools for scraping, natural language processing, machine learning, network analysis and visualization.',
  'language': 'Python',
  'stars': np.int64(8860),
  'url': 'https://github.com/clips/pattern',
  'similarity': 0.4266}]

In [53]:
print(model)

SentenceTransformer(
  (0): Transformer({'transformer_task': 'feature-extraction', 'modality_config': {'text': {'method': 'forward', 'method_output_name': 'last_hidden_state'}}, 'module_output_name': 'token_embeddings', 'architecture': 'BertModel'})
  (1): Pooling({'embedding_dimension': 384, 'pooling_mode': 'mean', 'include_prompt': True})
)

In [54]:
print(type(embeddings))
print(embeddings.shape)

<class 'numpy.ndarray'>
(461, 384)

In [55]:
query_embedding = model.encode(
    "Find me a Python deep-learning project for image classification."
)

print(query_embedding.shape)

(384,)

In [56]:
print(model._modules["0"].auto_model.config._name_or_path)

sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2

In [58]:
pd.read_csv("../Data/repositories.csv").columns

Index(['name', 'description', 'stars', 'forks', 'language', 'topics',
       'updated_at', 'license', 'url', 'readme'],
      dtype='str')

In [59]:
pd.read_csv("../Data/repositories.csv")["readme"].notna().sum()

np.int64(461)

In [1]:
import pandas as pd

df = pd.read_csv("../Data/repositories.csv")

matches = df[
    df["name"].str.contains("fake|news", case=False, na=False)
    | df["description"].str.contains("fake|news", case=False, na=False)
    | df["readme"].str.contains("fake news", case=False, na=False)
]

matches[["name", "description", "language", "url"]]

,name,description,language,url
3,fighting41love/funNLP,中英文敏感词、语言检测、中外手机/电话归属地/运营商查询、名字推断性别、手机号抽取、身份证抽...,Python,https://github.com/fighting41love/funNLP
62,ChristosChristofidis/awesome-deep-learning,A curated list of awesome Deep Learning tutori...,NaN,https://github.com/ChristosChristofidis/awesom...
153,shirosaidev/stocksight,Stock market analyzer and predictor using Elas...,Python,https://github.com/shirosaidev/stocksight
162,NiuTrans/ABigSurvey,A collection of 1000+ survey papers on Natural...,NaN,https://github.com/NiuTrans/ABigSurvey
173,hungtraan/FacebookBot,A Facebook Messenger Bot that supports Voice R...,JavaScript,https://github.com/hungtraan/FacebookBot
329,ZhuLinsen/daily_stock_analysis,LLM 驱动的多市场股票智能分析系统：多源行情、实时新闻、决策看板与自动推送，支持零成本定时...,Python,https://github.com/ZhuLinsen/daily_stock_analysis
366,eddwebster/football_analytics,📊⚽ A collection of football analytics project...,Jupyter Notebook,https://github.com/eddwebster/football_analytics