In [1]:
import pandas as pd

In [5]:
df=pd.read_csv(r'C:\Users\ayush\PROJECTS\Github-Recommender\Data\repositories.csv')
df

,name,description,readme,stars,forks,language,topics,updated_at,license,url
0,tensorflow/tensorflow,An Open Source Machine Learning Framework for ...,"<div align=""center"">\n <img src=""https://www....",198799,76234,C++,"['deep-learning', 'deep-neural-networks', 'dis...",2026-09-04T09:10:02Z,Apache License 2.0,https://github.com/tensorflow/tensorflow
1,huggingface/transformers,🤗 Transformers: the model-definition framework...,<!---\nCopyright 2020 The HuggingFace Team. Al...,164772,34436,Python,"['audio', 'deep-learning', 'deepseek', 'gemma'...",2026-09-04T09:03:22Z,Apache License 2.0,https://github.com/huggingface/transformers
2,microsoft/ML-For-Beginners,"12 weeks, 26 lessons, 52 quizzes, classic Mach...",[![GitHub license](https://img.shields.io/gith...,90115,22181,Jupyter Notebook,"['data-science', 'education', 'machine-learnin...",2026-09-04T09:10:03Z,MIT License,https://github.com/microsoft/ML-For-Beginners
3,fighting41love/funNLP,中英文敏感词、语言检测、中外手机/电话归属地/运营商查询、名字推断性别、手机号抽取、身份证抽...,"<center>\n <img style=""border-radius: 0.312...",82868,15279,Python,[],2026-09-04T08:55:47Z,NaN,https://github.com/fighting41love/funNLP
4,josephmisiti/awesome-machine-learning,A curated list of awesome Machine Learning fra...,# Awesome Machine Learning [![Awesome](https:/...,74251,15637,Python,[],2026-09-04T07:27:51Z,Other,https://github.com/josephmisiti/awesome-machin...
5,scikit-learn/scikit-learn,scikit-learn: machine learning in Python,.. -*- mode: rst -*-\n\n|GitHubActions| |Codec...,67158,27355,Python,"['data-analysis', 'data-science', 'machine-lea...",2026-09-04T08:51:58Z,"BSD 3-Clause ""New"" or ""Revised"" License",https://github.com/scikit-learn/scikit-learn
6,gradio-app/gradio,Build and share delightful machine learning ap...,<!-- DO NOT EDIT THIS FILE DIRECTLY. INSTEAD E...,43466,3585,Python,"['data-analysis', 'data-science', 'data-visual...",2026-09-04T08:34:36Z,Apache License 2.0,https://github.com/gradio-app/gradio
7,ashishpatel26/500-AI-Machine-learning-Deep-lea...,500 AI Machine learning Deep learning Computer...,## 500 + 𝗔𝗿𝘁𝗶𝗳𝗶𝗰𝗶𝗮𝗹 𝗜𝗻𝘁𝗲𝗹𝗹𝗶𝗴𝗲𝗻𝗰𝗲 𝗣𝗿𝗼𝗷𝗲𝗰𝘁 𝗟𝗶𝘀𝘁 ...,36713,7478,NaN,"['artificial-intelligence', 'artificial-intell...",2026-09-04T08:12:14Z,NaN,https://github.com/ashishpatel26/500-AI-Machin...
8,TheAlgorithms/C-Plus-Plus,Collection of various algorithms in mathematic...,# The Algorithms - C++ # {#mainpage}\n\n<!-- t...,34628,7855,C++,"['algorithm', 'algorithm-competitions', 'algor...",2026-09-04T05:00:50Z,MIT License,https://github.com/TheAlgorithms/C-Plus-Plus
9,lutzroeder/netron,"Visualizer for neural network, deep learning a...","<div align=""center"">\n<img width=""400px"" heigh...",33436,3182,JavaScript,"['ai', 'coreml', 'deep-learning', 'deeplearnin...",2026-09-04T09:04:47Z,MIT License,https://github.com/lutzroeder/netron

In [6]:
df['readme']

0    <div align="center">\n  <img src="https://www....
1    <!---\nCopyright 2020 The HuggingFace Team. Al...
2    [![GitHub license](https://img.shields.io/gith...
3    <center>\n    <img style="border-radius: 0.312...
4    # Awesome Machine Learning [![Awesome](https:/...
5    .. -*- mode: rst -*-\n\n|GitHubActions| |Codec...
6    <!-- DO NOT EDIT THIS FILE DIRECTLY. INSTEAD E...
7    ## 500 + 𝗔𝗿𝘁𝗶𝗳𝗶𝗰𝗶𝗮𝗹 𝗜𝗻𝘁𝗲𝗹𝗹𝗶𝗴𝗲𝗻𝗰𝗲 𝗣𝗿𝗼𝗷𝗲𝗰𝘁 𝗟𝗶𝘀𝘁 ...
8    # The Algorithms - C++ # {#mainpage}\n\n<!-- t...
9    <div align="center">\n<img width="400px" heigh...
Name: readme, dtype: str

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         10 non-null     str
 1   description  10 non-null     str
 2   readme       10 non-null     str
 3   stars        10 non-null     int64
 4   forks        10 non-null     int64
 5   language     9 non-null      str
 6   topics       10 non-null     str
 7   updated_at   10 non-null     str
 8   license      8 non-null      str
 9   url          10 non-null     str
dtypes: int64(2), str(8)
memory usage: 932.0 bytes

In [9]:
df.describe()

               stars         forks
count      10.000000     10.000000
mean    82620.600000  21322.200000
std     56739.803353  21883.413246
min     33436.000000   3182.000000
25%     38401.250000   7572.250000
50%     70704.500000  15458.000000
75%     88303.250000  26061.500000
max    198799.000000  76234.000000

In [13]:
df["readme"].fillna("").str.len().describe()

count        10.000000
mean      41828.600000
std       67769.960699
min        3338.000000
25%        8204.000000
50%       15089.500000
75%       27787.500000
max      219188.000000
Name: readme, dtype: float64

In [14]:
df["readme"].isna().sum()

np.int64(0)